version: '3'

services:
  frontend:
    build:
      context: ./frontend_movie-recommendation
    ports:
      - "3000:3000" 
    depends_on:
      - backend 

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"  # Port sur lequel l'application FastAPI sera exposée
    environment:
    - DATABASE_URL=mysql+mysqlconnector://emmaProj_archMICserv:Emm@1234*@localhost:3306/Recom_db  # URL de la base de données MySQL
